## Stream Platform Merger Data Analysis

#### Loading Libraries and the Datasets

In [2]:
import pandas as pd
import matplotlib as plt

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [4]:
# import the Jotstar Data
jotstarConsumption = pd.read_csv ("Jotstar CSV files/content_consumption.csv")
jotstarContents = pd.read_csv ("Jotstar CSV files/contents.csv")
jotstarSubscribers = pd.read_csv ("Jotstar CSV files/subscribers.csv")

In [ ]:
# import the LioCinema Data
LioCinemaConsumption = pd.read_csv ("LioCinema CSV files/content_consumption.csv")
LioCinemaContents = pd.read_csv ("LioCinema CSV files/contents.csv")
LioCinemaSubscribers = pd.read_csv ("LioCinema CSV files/subscribers.csv")

### 1.  Data Pre-Processing and Initial EDA

- Checking the shape of teh datasets

In [6]:
print(jotstarConsumption.shape)
print(LioCinemaConsumption.shape)

print(jotstarContents.shape)
print(LioCinemaContents.shape)

print(jotstarSubscribers.shape)
print(LioCinemaSubscribers.shape)

(1000, 3)
(1000, 3)
(1000, 5)
(1000, 5)
(1000, 8)
(1000, 8)

- Checking For Null Values

In [7]:
jotstarConsumption.isnull().sum()

user_id                  0
device_type              0
total_watch_time_mins    0
dtype: int64

In [8]:
LioCinemaConsumption.isnull().sum()

user_id                  0
device_type              0
total_watch_time_mins    0
dtype: int64

In [9]:
jotstarContents.isnull().sum()

content_id      0
content_type    0
language        0
genre           0
run_time        0
dtype: int64

In [10]:
LioCinemaContents.isnull().sum()

content_id      0
content_type    0
language        0
genre           0
run_time        0
dtype: int64

In [11]:
jotstarSubscribers.isnull().sum()

user_id                    0
age_group                  0
city_tier                  0
subscription_date          0
subscription_plan          0
last_active_date         854
plan_change_date         842
new_subscription_plan    842
dtype: int64

In [12]:
LioCinemaSubscribers.isnull().sum()

user_id                    0
age_group                  0
city_tier                  0
subscription_date          0
subscription_plan          0
last_active_date         572
plan_change_date         856
new_subscription_plan    856
dtype: int64

## 2. Analysis Phase

### 1. Content Library Analysis

In [13]:
jotstarContents.head()

       content_id content_type language   genre  run_time
0  CJSMBEACT2e633        Movie  Bengali  Action        90
1  CJSMBEACT34aec        Movie  Bengali  Action       135
2  CJSMBEACT83b46        Movie  Bengali  Action       120
3  CJSMBECOM12e7a        Movie  Bengali  Comedy       120
4  CJSMBECOM5431a        Movie  Bengali  Comedy       135

In [14]:
LioCinemaContents.head()

       content_id content_type language   genre  run_time
0  CLCMENACT6b77e        Movie  English  Action       120
1  CLCMENACTb7ceb        Movie  English  Action       135
2  CLCMENCOM1563a        Movie  English  Comedy       135
3  CLCMENCOM16d2c        Movie  English  Comedy       135
4  CLCMENCOMa0548        Movie  English  Comedy       135

In [15]:
jotstarContents['platform'] = "Jotstar"
LioCinemaContents['platform'] = "LioCinema"

In [16]:
LioCinemaContents.head()

       content_id content_type language   genre  run_time   platform
0  CLCMENACT6b77e        Movie  English  Action       120  LioCinema
1  CLCMENACTb7ceb        Movie  English  Action       135  LioCinema
2  CLCMENCOM1563a        Movie  English  Comedy       135  LioCinema
3  CLCMENCOM16d2c        Movie  English  Comedy       135  LioCinema
4  CLCMENCOMa0548        Movie  English  Comedy       135  LioCinema

In [17]:
jotstarContents.head()

       content_id content_type language   genre  run_time platform
0  CJSMBEACT2e633        Movie  Bengali  Action        90  Jotstar
1  CJSMBEACT34aec        Movie  Bengali  Action       135  Jotstar
2  CJSMBEACT83b46        Movie  Bengali  Action       120  Jotstar
3  CJSMBECOM12e7a        Movie  Bengali  Comedy       120  Jotstar
4  CJSMBECOM5431a        Movie  Bengali  Comedy       135  Jotstar

In [18]:
# Combine both the data frames
combined_contents = pd.concat([LioCinemaContents, jotstarContents], ignore_index = "True")

In [19]:
combined_contents.tail()

          content_id content_type language    genre  run_time platform
1995  CJSMTAROM3e261        Movie    Tamil  Romance       150  Jotstar
1996  CJSMTAROM3eaa3        Movie    Tamil  Romance        90  Jotstar
1997  CJSMTAROM41005        Movie    Tamil  Romance       120  Jotstar
1998  CJSMTAROM493ce        Movie    Tamil  Romance       120  Jotstar
1999  CJSMTAROM4952b        Movie    Tamil  Romance       150  Jotstar

In [20]:
combined_contents.shape

(2000, 6)

In [21]:
# Content Type Analysis
combined_contents['content_type']. unique()

array(['Movie', 'Series'], dtype=object)

- 1.1 Group Content by Content_Type (Movie Or Series) for each platform

In [22]:
content_type_counts = combined_contents.groupby(['platform','content_type']).size().reset_index(name = "count")

In [23]:
content_type_counts

    platform content_type  count
0    Jotstar        Movie   1000
1  LioCinema        Movie    900
2  LioCinema       Series    100

- 1.2 Group Content by language for each platform

In [24]:
language_type_counts = combined_contents.groupby(['platform','language']).size().reset_index(name = "count")

In [25]:
language_type_counts

     platform   language  count
0     Jotstar    Bengali     35
1     Jotstar    English    359
2     Jotstar   Gujarati     11
3     Jotstar      Hindi    295
4     Jotstar    Kannada     70
5     Jotstar  Malayalam     70
6     Jotstar    Marathi     47
7     Jotstar    Punjabi     11
8     Jotstar      Tamil    102
9   LioCinema    English     56
10  LioCinema      Hindi    364
11  LioCinema    Kannada     81
12  LioCinema  Malayalam     90
13  LioCinema    Marathi     49
14  LioCinema      Tamil    171
15  LioCinema     Telugu    189

- 1.3 Group content by Genre for each platform

In [26]:
genre_type_counts = combined_contents.groupby(['platform','genre']).size().reset_index(name = "count")

In [27]:
genre_type_counts

     platform      genre  count
0     Jotstar     Action    194
1     Jotstar  Adventure     78
2     Jotstar     Comedy    127
3     Jotstar      Drama    202
4     Jotstar     Family      7
5     Jotstar    Fantasy    108
6     Jotstar    Romance     94
7     Jotstar     Sci-Fi     58
8     Jotstar   Thriller    132
9   LioCinema     Action    143
10  LioCinema     Comedy    183
11  LioCinema      Crime     35
12  LioCinema      Drama    328
13  LioCinema     Family     67
14  LioCinema     Horror     27
15  LioCinema    Romance    119
16  LioCinema   Thriller     98

- 1.4 Group Content by Run Time for each platform

In [28]:
run_time_counts = combined_contents.groupby(['platform','run_time']).size().reset_index(name = "count")

In [29]:
run_time_counts

     platform  run_time  count
0     Jotstar        90    206
1     Jotstar       120    400
2     Jotstar       135    202
3     Jotstar       150    142
4     Jotstar       180     50
5   LioCinema        20     21
6   LioCinema        30     54
7   LioCinema        45     25
8   LioCinema        90    135
9   LioCinema       120    360
10  LioCinema       135    225
11  LioCinema       150    135
12  LioCinema       180     45